### ISSUE TITLE
Headings are not working

### ISSUE THREAD

**Issue by notbotman** [parsedown/laravel#12]
![image](https://user-images.githubusercontent.com/74244707/103166635-17435300-484a-11eb-8e97-c91896f0ec2c.png)

Any ideas on how I can enable it?

**Comment by elvisblanco1993** [comment]
> ![image](https://user-images.githubusercontent.com/74244707/103166635-17435300-484a-11eb-8e97-c91896f0ec2c.png)
> 
> Any ideas on how I can enable it?

Are you using Tailwind by any chance? If so, please notice that Tailwind does not style headings by default.

**Comment by eagostini** [comment]
Does it have to do with this **Laravel** wrapper or the core library?
