### ISSUE TITLE
Adding an extension

### ISSUE THREAD

**Issue by nvayalil** [parsedown/laravel#13]
Where I add an [extension](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions)? any help?

**Comment by eagostini** [comment]
Hi @nvayalil! Apologies for the late reply.

I believe you can achieve this by extending the official class, applying your own changes according to the [documentation](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions) and re-assigning the instance to the main container in **Laravel**. You can find more information in the issue #10. Please, let me know if that works for you.
